// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cinema.proto

package io.cinema.proto;

public final class Cinema {
  private Cinema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Seat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Seat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubmitReserveTicketRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubmitReserveTicketRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReserveTicketResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReserveTicketResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAvailableSeatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAvailableSeatsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014cinema.proto\"#\n\004Seat\022\013\n\003row\030\001 \001(\005\022\016\n\006c" +
      "olumn\030\002 \001(\005\"2\n\032SubmitReserveTicketReques" +
      "t\022\024\n\005seats\030\002 \003(\0132\005.Seat\"<\n\025ReserveTicket" +
      "Response\022\022\n\nis_success\030\001 \001(\010\022\017\n\007message\030" +
      "\002 \001(\t\"1\n\031GetAvailableSeatsResponse\022\024\n\005se" +
      "ats\030\001 \003(\0132\005.Seat\"\007\n\005Empty2\241\001\n\rCinemaServ" +
      "ice\022J\n\023SubmitReserveTicket\022\033.SubmitReser" +
      "veTicketRequest\032\026.ReserveTicketResponse\022" +
      "D\n\036SubmitGetAvailableSeatsRequest\022\006.Empt" +
      "y\032\032.GetAvailableSeatsResponseB\023\n\017io.cine" +
      "ma.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Seat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Seat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Seat_descriptor,
        new java.lang.String[] { "Row", "Column", });
    internal_static_SubmitReserveTicketRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SubmitReserveTicketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubmitReserveTicketRequest_descriptor,
        new java.lang.String[] { "Seats", });
    internal_static_ReserveTicketResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReserveTicketResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReserveTicketResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Message", });
    internal_static_GetAvailableSeatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAvailableSeatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAvailableSeatsResponse_descriptor,
        new java.lang.String[] { "Seats", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
