// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cinema.proto

package io.cinema.proto;

public interface CinemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Cinema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Seat available_seats = 1;</code>
   */
  java.util.List<io.cinema.proto.Seat> 
      getAvailableSeatsList();
  /**
   * <code>repeated .Seat available_seats = 1;</code>
   */
  io.cinema.proto.Seat getAvailableSeats(int index);
  /**
   * <code>repeated .Seat available_seats = 1;</code>
   */
  int getAvailableSeatsCount();
  /**
   * <code>repeated .Seat available_seats = 1;</code>
   */
  java.util.List<? extends io.cinema.proto.SeatOrBuilder> 
      getAvailableSeatsOrBuilderList();
  /**
   * <code>repeated .Seat available_seats = 1;</code>
   */
  io.cinema.proto.SeatOrBuilder getAvailableSeatsOrBuilder(
      int index);

  /**
   * <code>repeated .Seat reserved_seats = 2;</code>
   */
  java.util.List<io.cinema.proto.Seat> 
      getReservedSeatsList();
  /**
   * <code>repeated .Seat reserved_seats = 2;</code>
   */
  io.cinema.proto.Seat getReservedSeats(int index);
  /**
   * <code>repeated .Seat reserved_seats = 2;</code>
   */
  int getReservedSeatsCount();
  /**
   * <code>repeated .Seat reserved_seats = 2;</code>
   */
  java.util.List<? extends io.cinema.proto.SeatOrBuilder> 
      getReservedSeatsOrBuilderList();
  /**
   * <code>repeated .Seat reserved_seats = 2;</code>
   */
  io.cinema.proto.SeatOrBuilder getReservedSeatsOrBuilder(
      int index);

  /**
   * <code>int32 min_distance = 3;</code>
   * @return The minDistance.
   */
  int getMinDistance();
}
