// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cinema.proto

package io.cinema.proto;

public interface GetAvailableSeatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAvailableSeatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Seat seats = 1;</code>
   */
  java.util.List<io.cinema.proto.Seat> 
      getSeatsList();
  /**
   * <code>repeated .Seat seats = 1;</code>
   */
  io.cinema.proto.Seat getSeats(int index);
  /**
   * <code>repeated .Seat seats = 1;</code>
   */
  int getSeatsCount();
  /**
   * <code>repeated .Seat seats = 1;</code>
   */
  java.util.List<? extends io.cinema.proto.SeatOrBuilder> 
      getSeatsOrBuilderList();
  /**
   * <code>repeated .Seat seats = 1;</code>
   */
  io.cinema.proto.SeatOrBuilder getSeatsOrBuilder(
      int index);
}
