// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cinema.proto

package io.cinema.proto;

public interface ReserveTicketResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReserveTicketResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_success = 1;</code>
   * @return The isSuccess.
   */
  boolean getIsSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
