// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cinema.proto

package io.cinema.proto;

public interface SeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Seat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 row = 1;</code>
   * @return The row.
   */
  int getRow();

  /**
   * <code>int32 column = 2;</code>
   * @return The column.
   */
  int getColumn();
}
